version: '3.7'

networks:
  network:
    driver: overlay

volumes:
  redis-data:
    driver: local

services:
  nginx:
    image: "nginx:1.15.8-alpine"
    deploy:
      replicas: 5
    ports:
      - 80:80
    networks:
      - network

  redis:
    image: "redis:5.0.3"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - redis-data:/data
    networks:
      - network
